# Generated by Django 4.2.7 on 2023-11-26 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address",
            new_name="order",
        ),
    ]
