# Generated by Django 4.2.7 on 2023-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_address_address_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_datetime",
            field=models.DateTimeField(editable=False),
        ),
    ]
