# Generated by Django 4.2.7 on 2023-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="vat_rate",
            field=models.IntegerField(
                choices=[
                    (23, "23% - Standard rate"),
                    (8, "8% - Reduced rate"),
                    (5, "5% - Reduced rate"),
                    (0, "0% - Zero rate"),
                ],
                default=23,
                verbose_name="vat rate",
            ),
        ),
    ]
